services:
  iona:
    build: .
    container_name: discordbot-iona
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      WEBHOOK_PORT: 3000

    env_file:
      - .env

    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"